spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mydatabase?autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useTimezone=true&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: "classpath:db/migration"
    validateMigrationNaming: true
  docker:
    compose:
      lifecycle-management: start-only # none, start-only , start-and-stop
server:
  error:
    include-exception: false
    include-stacktrace: never
    path: '/api/error'
    whitelabel:
      enabled: false
  port: 38081
redis:
  host: 127.0.0.1
  port: 6379
  auth: false
  authentication:
    database: 0
  user:
    database: 1
  noti:
    database: 5
  sso:
    database: 6
  type: STANDARD
jwt:
  secret: mysecret