CREATE DATABASE IF NOT EXISTS mydatabase;

CREATE USER IF NOT EXISTS 'myuser'@'%' IDENTIFIED BY 'changeme';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT
  ON `mydatabase`.* TO 'myuser'@'%';

FLUSH PRIVILEGES;
